version: '3.8'
services:
  web:
    build: .
    command: python3 -m flask run --host=0.0.0.0
    volumes:
      - .:/app
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: fitness_tracker_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres