name: Python application CI

on:
  push:
    branches: [ main, feature/* ]  # Run CI on push to main and any feature branches
  pull_request:
    branches: [ main ]             # Run CI on pull requests to main

jobs:
  build-and-test:
    runs-on: ubuntu-latest         # The type of runner that the job will run on

    services:                      # Defines the service containers to run
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: fitness_tracker_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432             # Maps PostgreSQL port 5432 to the runner
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2  # Checks-out your repository under $GITHUB_WORKSPACE

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'    # Install Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with pytest
      run: |
        pytest
